<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        /* Set A4 page size */
        @page {
            /* size: A4;*/
            margin: 15mm;
        }

        /* Reset margins and padding */
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            font-size: 10pt;
            /* line-height: 1.6; */
        }

        /* Page header and title */
        h1 {
            text-align: center;
            font-size: 16pt;
            margin-bottom: 10px;
        }

        /* Styling for table */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }

        table th, table td {
            border: 1px solid #000;
            padding: 3px;
            text-align: left;
        }

        table th {
            background-color: #f2f2f2;
        }

        /* Styling for paragraph and other text */
        p {
            font-size: 8pt;
            margin: 0;
            padding: 0;
        }

        /* Style for the footer */
        footer {
            text-align: center;
            position: fixed;
            bottom: 0;
            width: 100%;
            font-size: 8pt;
            margin-top: 10px;
        }

        /* Optional: Add a border to the page */
        .page-border {
            border: 1px solid #000;
            padding: 3px;
        }
    </style>
</head>
<body>
    <div class="page-border">
        <h1>{{ $title }}</h1>

        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Company</th>
                    <th>Parent Company</th>
                    <th>Industry</th>
                    <!-- <th>Primary Email</th> -->
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($result as $k=>$ar)
                    <tr>
                        <td>{{($k+1)}}</td>
                        <td>{{ $ar['first_name'] }}</td>
                        <td>{{ $ar['last_name'] }}</td>
                        <td>{{ $ar['email'] }}</td>
                        <td>{{ $ar['company'] }}</td>
                        <td>{{ $ar['parent_company'] }}</td>
                        <td>{{ $ar['industry'] }}</td>
                        <!-- <td>$ar['primary_email']</td> -->
                        <td>{{ $ar['status'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <footer>
        <p>Generated by Devotion group</p>
    </footer>
</body>
</html>